project:
  type: website

execute:
  echo: false
  warning: false
  message: false

website:
  title: "R for the Rest of Us Handbook"
  search: false
 

  sidebar:
    style: "docked"
    search: true
    border: true
    logo: assets/rru-logo-text-right-stacked.png
    
    contents:
      - index.qmd
      - section: "Clients"
        contents:
        - clients.qmd
      - section: "Operations"
        contents:
        - david-work.qmd
        - tools.qmd
        - communication.qmd
        - finances.qmd
        - contracts.qmd
        - proposals.qmd
      - section: "Marketing"
        contents:
        - marketing-overview.qmd
        - branding.qmd
        - website.qmd
        - content-strategy.qmd
        - email-marketing.qmd
        - social-media.qmd
      - section: "Courses"
        contents: 
        - courses-overview.qmd
        - courses-legal-financial.qmd
        - courses-curriculum.qmd
        - courses-recording.qmd
        - courses-editing.qmd
        - courses-production.qmd
        - courses-marketing.qmd
      - section: "R in 3 Months"
        contents:
        - href: rin3months.qmd
          text: "Overview"
      - section: "Consulting"
        contents:
        - consulting-overview.qmd
        - project-management.qmd
      - section: "Code"
        contents:
        - code-style.qmd
        - github.qmd
        - data-viz.qmd
format:
  html:
    toc: true
    toc-depth: 4
    theme: litera
    css: styles.css



