---
title: "Branding"
---

The best description of branding that I've read is from [Gumroad](https://www.notion.so/e3e2678e40df453eaea065bd0e7a8f10):

> A brand is nothing more than people's perceptions. Since Gumroad is defined by how the world feels about us, we like to make a good impression.
> 

When I think about who typical customers are for education products, here's the persona I have in mind: 

> 40-something year old woman with a Master's degree who does some type of social science-related work. She is really good with Excel and probably learned to use some other statistical software (SPSS, SAS, Stata, etc) in grad school. She's heard about other people using R and is intrigued but at the same time is scared by what she's heard about how hard R is to learn.
> 

With this persona in mind, I've intentionally tried to make the R for the Rest of Us personality:

- Friendly
- Welcoming
- Not too serious

All of the marketing I do takes a laid-back, conversational approach. I start all emails, for example, with the phrase "Hi friend". Any time someone asks a question, I reassure them it's a good question (people are afraid to ask "dumb" questions when it comes to R). These are a couple ways I try to implement the brand.

## Logo, colors, typography

When most people think of branding, this is what they're asking about. You can find the various logos, colors, and typography that I use on Canva.
