---
title: "Communication"
---

## Internal Communication

As a fully remote company, we try to communicate by writing as much as possible. Doing so has many benefits:

1. It forces us to clarify our thinking
2. It provides a record of decisions for those who may join things midstream
3. It allows people to work on their own time without feeling the need to join live calls etc

Internal communication happens, as much as possible, in Twist. There are several channels:

- Consulting
- Course Questions
- Courses
- General
- Marketing
- Orders (all paid course orders go through here)
- R in 3 Months
- Random
- Training
- Website

Within each channel, we typically use one thread per project (sometimes more depending on its complexity).

Other places internal communication happens include:

- GitHub for discussion of specific issues on code-based projects
- Todoist comments for questions on specific tasks to be done

## External Communication

External communication with clients and others happens mostly through email. For clients who use GitHub, we communicate using GitHub issues.