---
title: "Content"
---

We produce two types of content: free and paid content. The free content is inteded to drive awareness of and signups for paid content. 

## Free Content

We use free content to build authority so that people see R for the Rest of Us as worth purchasing things (courses, custom training, consulting services) from us.

In 2024, I plan to produce 4 different types of content:

1. **Long-form blog posts** and accompanying **YouTube videos** (one blog post/video every other week)
2. **R in 2 Minutes YouTube videos** and accompanying **blog posts** that highlight one tip in 2 minutes or less (one video every four weeks)
3. **What's New in R** emails that highlight three interesting packages/tutorials/etc in each email (one email every other week)
4. **Podcast** episodes (also released as **YouTube videos**) featuring interviews with people doing unique things with R (one episode every four weeks)

Each of these items gets sent out via [email](email-marketing.qmd) and [social media](social-media.qmd).

## Content Calendar

We have a content calendar to get an overall sense of what's going out when. You can find that on [Airtable](https://airtable.com/appT0WIaSbe04ZU4r/tbliMwZdWOcjN5FS8/viw53Loqe6w5UEbZL?blocks=hide).

[I recorded a video to show how this works](https://muse.ai/vt/4roR5EG).

### Long-Form Blog Posts and YouTube Videos

1. When there is a new blog post, David adds the information about it (link to the blog post, Descript link, and email text) to the Todoist task.
1. David writes a blog post in the [blog repo](https://github.com/rfortherestofus/blog) as a Quarto document. 
1. David adds the blog post as a draft to the website using the procedures outlined [here](https://github.com/rfortherestofus/rfortherestofus.com?tab=readme-ov-file#quarto-importer).
1. Joe determines the date that the blog post should go out, based on the schedule laid out above. This is important because the link to the blog post depends on the date it is published, and that link will be added to the YouTube video description below.
1. Assuming there is an accompanying video, David records that in Descript. 
1. Joe edits the video in Descript.
1. David approves the edited video.
1. Joe uploads the video to YouTube. 
1. Joe creates a featured image for the blog post and a thumbnail for the YouTube video and adds them.
1. Joe writes the description for the YouTube video. The description should summarize the video content and, most importantly, provide a link to the accompanying blog post where people can read the tutorial and see the code used in the video. 
1. Joe schedules the YouTube video to go live a few hours before the blog post to ensure the videos show up.
1. Joe adds the YouTube video at the top of the blog post.
1. Joe sets the email up in ConvertKit.
1. Joe creates a LinkedIn post to go out the day the email goes out. The content of the LinkedIn post should be adapted from the email content.
1. Joe creates two video clips to go out on LinkedIn the Friday and Tuesday after a new blog post is released. 

### R in 2 Minutes Blog Posts and YouTube Videos

Here are the steps to make and promote R in 2 Minutes videos.

1. First, David records the video on Descript.
1. David writes a title and short text intro for the video.
1. Next, Joe edits the video, adding the R in 2 Minutes intro and outro.
1. Joe creates a thumbnail using the R in 2 Minutes template in the [YouTube thumbnails project on Canva](https://www.canva.com/design/DAF9nXMmRH0/9wfI47oEUa20zFF20tcKGQ/edit?utm_content=DAF9nXMmRH0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
1. Joe uploads the video to YouTube, setting the release date on the day the blog post is set to go live.
1. Joe makes sure the YouTube video has a link to the blog post in the description. 
1. Joe adds the thumbnail to the YouTube video.
1. Joe takes the text intro and creates a new blog post. 
1. Joe adds the thumbnail as the social image for the blog post in the SEO section. 
1. Joe sets up an email to go out at 5:00am the day the blog post goes live (see text below).
1. On the day that the R in 2 Minutes blog post and video is scheduled, Joe also sets the video to go up on LinkedIn. The LinkedIn post should just use the intro text as the body of the post.
1. Joe adds everything to the content calendar.

You can watch a video walkthrough of this here:

<div class="muse-video-player" data-video="T4iH2pe" data-links="0" data-logo="0" data-title="0" data-width="100%"></div><script src="https://muse.ai/static/js/embed-player.min.js"></script>

<br>

**R in 2 Minutes email text**

Here is the template that should go in emails announcing new R in 2 Minutes blog posts/videos.

> Hi friend,
> 
> I'm back with another short R in 2 Minutes video tutorial. This week, [TEXT GOES HERE].
> 
> Hope this video is helpful! If you have any feedback, just hit reply and let me know.
> 
> Cheers,
>
> David

### What's New in R Emails

1. David writes content that is posted on the [What's New in R Netlify website](https://whatsnewwithr.netlify.app/)
1. Joe then [schedules broadcast email on ConvertKit](https://app.convertkit.com/campaigns). It goes out at 5am Pacific time on the day specified ([walkthrough video](https://show.rfor.us/NhDzNg0H)).
1. [Post is added to website](https://rfortherestofus.com/cp/collections/blog).
1. [All resources mentioned in What's New in R email should be added as resources on the R for the Rest of Us website](https://rfortherestofus.com/cp/collections/resources/entries/create/default).
1. [PDF is created in Canva](https://www.canva.com/design/DAF5g0IFWo4/J7uby69jtK9Vvh5jfcw4Wg/view?mode=preview).
1. [LinkedIn post is scheduled](https://publish.buffer.com/profile/62006137b475f9032331c5db/tab/queue). PDF should be attached. Text should look like this:

> Text of this post should say something like:
> 
> This week on What's New in R, we're featuring:
> 
> ✅ Blog post by @Albert Rapp on creating interactive visualizations with {ggiraph} (with or without Shiny)
> 
> ✅ Recordings of posit::conf(2023) by @Posit PBC
> 
> ✅ Quarto for Scientists materials, compiled by @Nick Tierney
> 
> Read the issue: https://rfortherestofus.com/2024/04/whats-new-in-r-april-1-2024
> 
> Sign up to get What's New in R in your inbox: What's New in R
> 
> #rstats

### Podcast (Audio and Video)

Podcast episodes are recorded using Squadcast. 

From there, the raw video files are downloaded and imported into Descript. Joe lines up the files manually so that the screencast portion of the interview is aligned with the other video files. Podcast episodes should be edited using the video files. Please use the [side by side template](https://web.descript.com/11d9eca5-cccd-4bd0-8c71-09fa78670076). 

Once a complete video version is created, a copy is made to create an audio version. In the audio version, the first half of the podcast is included, but as soon as the screenshare starts, we insert an audio clip of David saying "look at show notes for link to screencast."

#### Ads

The goal of all content is to get people on the R for the Rest of Us email list. Toward this end, we insert ads in podcast episodes (both audio and video versions). 

In the audio versions, we find a place about halfway through and insert an ad telling people to sign up for the newsletter and put a link to the R for the Rest of Us newsletter in the podcast notes.

In the video versions, we add a link to the R for the Rest of Us newsletter in the video description.

#### Release Schedule

Podcast episodes are released every other week, on weeks when there is not a new blog post. 

### Subtitles

For all videos on YouTube, we add subtitles. To do this:

1. Joe downloads episode Transcript from Muse using the Plain text (.txt) option
1. On YouTube, Joe adds the .txt file (open video from channel content list, click on pencil icon on the Subtitles button, choose Upload file, select ‘Without timing’ in the ‘Select subtitle file type’ dialog box, hit continue to upload the .txt file saved on computer, edit transcript where necessary, save changes) (edited)

## Paid Content

Courses are obviously paid content, as are consulting and custom training.