---
title: "Terms"
---

Here are the legal and financial terms that I typically use when working with course instructors (this is the broad overview; you will receive a full contract with this all spelled out). I'm flexible and happy to work with you to come up with a solution that meets both of our needs. 

## Compensation

I pay an advance to the course creator of $500, half on signing the contract to work together, and the other half when the course is released.  

Revenue for the courses is split 60/40 (60% for R for the Rest of Us, 40% for the course creator). I pay any royalties owed to the course creator on a quarterly basis. 

## Ownership

All videos are owned by R for the Rest of Us. All non-video materials will be made freely available on the R for the Rest of Us organization GitHub using a CC-BY-SA-4.0 License.

## Exclusivity

The instructor agrees not to create a course that covers the same topic on another online platform for at least 12 months from the release of this course. 

## Agreement Expiration

These terms remain in effect for one year after the course is released. After that, David and the instructor will discuss any possible changes to the terms.


