---
title: "Editing"
---

## Video Editing

After the instructor records videos on Descript, David and team edit them. 

Most lessons will have the following structure:

- Intro sting
- Full video on instructor as they introduce topic
- Full screen on slides/RSutdio as instructor presents lesson
- Full screen on Your Turn section
- Outro sting

After editing each video, the intro and outro animation should be added.

## Descript Tips
The easiest way to start out is to remove word gaps. I do this for any gaps greater than 1 second. This ensures that any times the instructor paused to gather their thoughts etc, those blank spaces are removed.

Leave 0.25 seconds gaps between clips where the instructor is on camera and clips where they're showing their screen.

When there are two back-to-back clips of the speaker on camera, do a 0.5 second crossfade so the jump isn’t too abrupt.

Where appropriate, use stock videos/photos on Descript to highlight a concept.

You can zoom into sections of the screen on Descript. For example, in a video showing the pieces of RStudio, it may make sense to zoom into each one as I discuss it. Make Zooms quicker — around 1 second. Use Zooms sparingly as it takes a lot of time!

Where appropriate, use callout boxes, arrows, and text to draw the learner's attention to a specific area of the screen (for example, when the instructor says "you can see here..."). Use color code ff7400 consistently when adding these attention grabbers.

Annotations can be added as appropriate. For example, if the instructor mentions a link in the video, we can add an annotation to say "link is below" or something similar.

## Sound

Sound levels should be fairly consistent assuming recording conditions remain consistent. However, if necessary you can [auto-level clips](https://help.descript.com/hc/en-us/articles/10249334057357-Auto-leveling-individual-clips).

Studio sound: TODO figure out if we should use it

## Export

There are two ways to export videos:

1. Exporting directly

1. Publishing and then downloading

It is best to do the second option, as it is much quicker. Simply hit publish in the top right. Once the project is published, you can then hit the download button. If you make changes to the project, simply hit Update and then re-download. 
