---
title: "Finances"
---

R for the Rest of Us finances are managed using QuickBooks. 

We do the following tasks in the first week of each month: 

[Categorize and approve all expenses in QuickBooks](https://app.qbo.intuit.com/app/banking): If unclear on category, first look at previous months. If still unclear, ask David.

[Send invoices to clients with QuickBooks](https://app.qbo.intuit.com/app/invoices): Time should be checked on [Toggl reports](https://track.toggl.com/reports/summary/3434156/period/prevMonth) and an invoice should be generated for each client. Some projects are billed hourly while others are billed at a flat rate (details are in the associated Todoist tasks). 

**Pay contractors with Gusto:** All contractors will submit an invoice each month using [this form](https://forms.gle/GadwWgoAP7U937uA6). They are then paid with Gusto. 

## Quarterly Tasks

Each quarter we reconcile accounts in QuickBooks. This is done by getting statements from both Advantis Credit Union and Mercury and then entering balances [here](https://app.qbo.intuit.com/app/reconcile). This compares the balances in my bank accounts to those in QuickBooks to make sure everything matches up.

I also pay course instructors each quarter. This is done using the [`pay-course-instructors.R` script in the `rru-finances` project](https://github.com/rfortherestofus/rru-finances/blob/main/pay-course-instructors.R).

## Annual Tasks

We send out 1099s to all contractors by Gusto. I've set Gusto up to make sure this happens, but we should check to confirm this in mid-January.

We also need to add end-of-year taxes for Stripe and PayPal fees. This is done in early January ([see Todoist task](https://app.todoist.com/app/task/add-pay-pal-stripe-end-of-year-taxes-6JjPf5McMG2qG3c4)).