---
title: "R in 3 Months"
---

# Before the cohort starts

## Discord
All the Discord server structure should be reviewed and redesigned, if needed. Channels that were not used need to be removed or redesigned. 

#### Participants roles

As participants register, they will provide their Discord handles and join the server through a link provided in the "Sign up for Discord" lesson. At the beggining of each cohort, this link must be reviewed and updated, as it might have expired.
Coaches must rename participants' display names with their real names and surnames, and later assign them the role of "student" or "scholar". Participants would then gain access to the active channels.

## Assigning coaches

Each participant will be assigned one coach, who will be responsible for giving feedback to their assignments, answering their questions and having 1:1 meetings with them. 

# During the course

## Mondays - reminder day

###  Reminder email

One of the coaches send a reminder email every Monday, which contains the following:

* Subject line in the format "[R in 3 Months] Week XX reminder email"  
* Theme of the week and what will be discussed in the live session  
* Link to the Zoom room  
* Date and time of the live session in Pacific Time (and a link to a time converter)  
* Reminder of any assignment due that week  
* Links and information on how to look for help (link to book 1:1 meetings with coaches, invite to office hours, etc.)  

The goal of the reminder email is to make sure all participants have the most up-to-date information about the tasks of the week, so they don't miss anything. All participants' emails should be added as BCC.  

### Events on Discord 
One of the coaches set the events of the week every Monday on Discord. They include the live session and office hours, if they are happening that week. The goal of setting these events is to add an option for those who need extra notification, as events on Discord notify the participants when the event starts and redirects them to the Zoom room where the event is happening.

## Thursdays - live session day
On the day of the live session, David will start the Zoom room and the recording. The live session will last one hour, and recording will be made available on the website.  
The assigned coach will take notes during the live session of:  
* The participants list from the attendees list.  
* Every link shared in the chat.  
* Any important tips, comments and questions made by the participants.  

Once the live session ends, the recording will be automatically uploaded to a shared Google Drive folder, and the assigned coach will be responsible for downloading the recording, uploading it into Muse.ai, creating a lesson in the corresponding Week section, and linking the video from Muse.ai into the lesson. In the lesson resources section, the assigned coach will add any resources shared or mentioned during the live session.  

### Follow-up email  
On the afternoon after the live session, the assigned coach will send a follow-up email that contains important information shared on the live session, and replies to the reminder email sent on Monday. It should contain:  

* Subject line in the format "[R in 3 Months] Week XX follow-up email"  
* Theme of the week and what was discussed in the live session (including important housekeeping topics)  
* Link to the recording on the course website  
* Reminder of any assignment due that week  
* Links and information on how to look for help (link to book 1:1 meetings with coaches, invite to office hours, etc.)  

The goal of this email is to provide a short summary and references that participants can refer to in the future, and to convey the most important information for those who couldn't attend the live session.

## Other days - community support

Also on Mondays and Thursdays, but mainly during the other days of the week, the coaches will work on supporting the community by answering questions, animating the Discord server, replying to emails and checking-in on them regularly. Coaches usually block 15min/day for this task, although it can take more than one hour/day during the first month of the cohort.  

#### Co-working hours

Co-working hours last 60min and are scheduled to happen in two different periods of the day, on dates and times defined by the coaches. The goal of the co-working hour is to provide a space for participants to ask direct questions, work together on the assingments, and talk about subjects not covered in the lessons.  

**Co-working hours are not recorded**, but notes should be taken by the assigned coach to help the instructor group to identify where participants need more assistance and topics to be covered in the live sessions.

<!--- For the next cohort, I suggest that the co-working hours are hosted and organized by the scholarship recipients. That way we involve them more actively and make this space more community-owned.--->

#### 1:1 meetings  
1:1 meetings are booked by the participants to request 30min meetings with their assigned coaches. Coaches should set up the booking system in a way that every booking request generates a Zoom room and a reminder for the participant to share their questions, data and code in advance.  The booking system currently used is SavvyCalendar.

#### Answering questions on lessons  
Comments and questions posted on the lessons should be approved and answered. David is the instructor responsible for replying the questions related specifically to the lessons, especially if they refer to the videos. Coaches are encouraged to reply these questions and to help approve the comments.

#### Assignment feedback  
Once a feedback is submitted, coaches have approximately three work days to provide feedback. These feedbacks can be a mix of text, code and video. Videos should be uploaded to Muse.ai and transcripts should be marked as viewable. When the feedback is complete, the coach should click on "Save & Publish" to make the feedback viewable.
Each assignment submitted will generate a task on Todoist with a corresponding deadline. Once the feedback is submitted, the assigned coach should mark this task as complete.

# Final week
After the final live session, participants will still be able to submit any assingments and get feedback from their coaches by the end of that month. 1:1 meetings can still be scheduled and completed by an end date defined by the coaches.  
In this final week, coaches work on wrapping up any remaining feedback, answering questions, and reflecting back on what has worked and what needs to change.

# After the course is over
## Discord
All cohort participants must lose their "student" or "scholar" status and become "alumni". This will make them lose access to most channels on the server, except for the "general" channel. They will, however, gain access to the "alumni-lounge" channel.  

## GitHub
Coaches should remind their students to remove them from their GitHub repositories and stop sharing any files or folders on cloud storage.

## Deleting information

## Scholarships

### Emails

Below is the text of emails that go out to applicants for R in 3 Months scholarships.

#### Scholarship Recipients

> Subject: Congratulations, you have been awarded a scholarship for R in 3 Months!
>
> Hello,
> 
> I'm delighted to inform you that you have been awarded a full scholarship for R in 3 Months! Supporting people learning R is something we feel passionately about, and we're honored to be able to help you on your R learning journey.
> 
> Please register for R in 3 Months using coupon code TODO. The price should be 0 for you. Please make sure you register with this email address. Otherwise, the coupon code will not work for you. If you did not previously have an account on the R for the Rest of Us website, we created one for you. You should have received an email with login information. 
>
> After you register, you will receive an email with information about some things to do before our first live session on Thursday. If you have any questions in the meantime, please let me know. We look forward to working with you!
> 
> Cheers,
> 
> David

#### Course Access

> Subject: Your R in 3 Months Scholarship Application
>
> Hello,
> 
> Thank you for applying for a scholarship for R in 3 Months. We received many applications and, unfortunately, you were not among those selected. 
> 
> However, we really want to support you learning R so I'd like to give you free access to two courses (Fundamentals of R and Going Deeper with R). You can sign up for these for free using the coupon code TODO at checkout. Please note that you must use this email address for the coupon to work. 
> 
> If you have any questions, please let me know. Best wishes on your R journey!
> 
> Cheers,
> 
> David

#### People Who Do Not Receive Scholarships or Course Access

> Subject: Your R in 3 Months Scholarship Application
>
> Hello,
> 
> Thank you for applying for a scholarship for R in 3 Months. We received many applications and, unfortunately, you were not among those selected. Please consider applying again next time! Until then, I wish you best of luck on your R journey.
> 
> Cheers,
> 
> David